[project]
name = "pysparkvenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphframes>=0.6",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pyspark>=4.0.1",
]
